### ISSUE TITLE
I'd like to use this with my own proxied backed to completely hide the API key

### ISSUE THREAD

**Issue by grmkris** [covalenthq/goldrush-kit#38]
Possible?

**Comment by jagnani73** [comment]
Since the GoldRush Kit is a Client-side rendering lib that requires the Covalent API key to exist on the client, you cant hide you API key via a proxy

However, you can manage [security](https://www.covalenthq.com/platform/apikey/) for you key via the Covalent Platform and limit the key to only work for specific origins or IPs
